swagger: '2.0'
info:
  version: 1.0.0
  title: Projeto API de Produtos/Pedidos de um delivery 
securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
paths:
  /client/create:
    post:
      tags:
        - Client
      summary: Cria um novo cliente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do cliente a ser criado
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              endereco:
                type: object
                properties:
                  street:
                    type: string
                  city:
                    type: string
                  state:
                    type: string
                  country:
                    type: string
                  zipCode:
                    type: string
              paymentMethod:
                type: object
                properties:
                  type:
                    type: string
                  number:
                    type: string
                  name:
                    type: string
                  expirationDate:
                    type: string
                  cvv:
                    type: string
              email:
                type: string
              password:
                type: string
              bornDate:
                type: string
                format: date
              orderHistory:
                type: array
                items:
                  type: string
              avatar:
                type: string
      responses:
        201:
          description: Cliente criado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /client/auth: 
    post:
      tags:
        - Client
      summary: Autentica um cliente existente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações de login do cliente
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Cliente autenticado com sucesso
        400:
          description: Parâmetros inválidos
        401:
          description: Credenciais inválidas
        500:
          description: Erro interno no servidor
  /client/edit:
    put:
      tags:
        - Client
      summary: Edita um cliente existente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do cliente a serem editadas
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              adress:
                type: array
                items:
                  type: object
                  properties:
                    street:
                      type: string
                    houseNumber:
                      type: string
                    city:
                      type: string
                    district:
                      type: string
                    landMark:
                      type: string
              paymentMethod:
                type: array
                items: {}
              email:
                type: string
              password:
                type: string
              bornDate:
                type: string
                format: date-time
              orderHistory:
                type: object
              avatar:
                type: string
      security:
        - Token: []
      responses:
        200:
          description: Cliente editado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /client/show:
    get:
      tags:
        - Client
      summary: Retorna informações de um cliente
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Token de autenticação JWT
          required: true
          type: string
      security:
        - Token: []
      responses:
        200:
          description: Informações do cliente
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              adress:
                type: array
                items:
                  type: object
                  properties:
                    street:
                      type: string
                    houseNumber:
                      type: string
                    city:
                      type: string
                    district:
                      type: string
                    landMark:
                      type: string
              paymentMethod:
                type: array
                items: {}
              email:
                type: string
              bornDate:
                type: string
                format: date-time
              orderHistory:
                type: object
              avatar:
                type: string
        401:
          description: Autenticação inválida ou não fornecida
        500:
          description: Erro interno no servidor
  /client/delete/{id}:
    delete:
      tags:
        - Client
      summary: Exclui um cliente pelo ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID do cliente a ser excluído
          required: true
          type: string
        - in: header
          name: Authorization
          description: Token de autenticação JWT
          required: true
          type: string
      security:
        - Token: []
      responses:
        204:
          description: Cliente excluído com sucesso
        401:
          description: Autenticação inválida ou não fornecida
        404:
          description: Cliente não encontrado
        500:
          description: Erro interno no servidor
  /client/address:
    post:
      tags:
        - Client
      summary: Cria um novo endereço para o cliente atual
      security:
        - JWT: []
      parameters: []
      requestBody:
        description: Objeto JSON contendo os dados do endereço
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                  example: Getulio Vargas
                houseNumber:
                  type: string
                  example: 22
                city:
                  type: string
                  example: chapeco
                district:
                  type: string
                  example: Centro
                landmark:
                  type: string
                  example: casa branca
              required:
                - street
                - houseNumber
                - city
                - district
                - landmark
      responses:
        '201':
          description: Endereço criado com sucesso
          schema:
            type: object
            properties:
              message:
                type: string
                example: Endereço criado com sucesso
        '400':
          description: Dados inválidos enviados na requisição
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dados inválidos enviados na requisição
        '401':
          description: Não autorizado
          schema:
            type: object
            properties:
              message:
                type: string
                example: Não autorizado
        '500':
          description: Erro interno do servidor
          schema:
            type: object
            properties:
              message:
                type: string
                example: Erro interno do servidor
  /client/address/delete/{id}:
    post:
      tags:
        - Client
      summary: Deletar endereço do cliente
      description: Deleta um endereço do cliente pelo seu ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do endereço a ser deletado
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Endereço deletado com sucesso
        '401':
          description: Não autorizado
        '404':
          description: Endereço não encontrado
  /client/delivery:
    get:
      tags:
        - Client
      summary: Solicitar entrega
      description: Solicita uma entrega para o endereço do cliente
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Token de autenticação
      requestBody:
        description: Dados do pedido e endereço de entrega
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                        description: ID do produto
                      quantity:
                        type: integer
                        description: Quantidade do produto
                      unitPrice:
                        type: number
                        description: Preço unitário do produto
                deliveryAddress:
                  type: object
                  properties:
                    street:
                      type: string
                      description: Nome da rua
                    houseNumber:
                      type: string
                      description: Número da casa
                    city:
                      type: string
                      description: Cidade
                    district:
                      type: string
                      description: Bairro
                    landmark:
                      type: string
                      description: Ponto de referência
              required:
                - items
                - deliveryAddress
      responses:
        '200':
          description: Pedido de entrega realizado com sucesso
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado
  /user/create:
    post:
      tags:
        - User
      summary: Cria um novo usuário
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do usuário a ser criado
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: Usuário criado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /user/edit:
    put:
      tags:
        - User
      summary: Edita  Usuário Logado
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do cliente a ser criado
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              email:
                type: string
              password:
                type: string
      security:
        - Token: []
      responses:
        201:
          description: Usuário editado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /user/delete:
    delete:
      tags:
        - User
      summary: Deleta o Usuário Logado
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - Token: []
      responses:
        201:
          description: Usuário deletado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /delivery/create:
    post:
      summary: Cria uma nova entrega
      tags:
        - Delivery
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deliveryAddress:
                  type: string
                product:
                  type: array
                  items:
                    type: string
              required:
                - deliveryAddress
                - product
      responses:
        '200':
          description: Entrega criada com sucesso
        '400':
          description: Parâmetros inválidos
        '401':
          description: Não autorizado
  /delivery/showall:
    get:
      tags:
        - Delivery
      summary: Mostra todas as entregas
      description: Retorna todas as entregas cadastradas no sistema
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Mostra todos os pedidos feitos
        '401':
          description: Unauthorized
  /product/create:
    post:
      tags:
        - Product
      summary: Cria um novo produto
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Pizza 5 queijos"
                price:
                  type: number
                  example: 125.00
                status:
                  type: string
                  example: "available"
                description:
                  type: string
                  example: "Pizza com queijo gorgonzola, mussarela, cheddar"
              required:
                - name
                - price
                - status
                - description
      responses:
        '200':
          description: Produto criado com sucesso
        '400':
          description: Erro ao criar produto
        '401':
          description: Não autorizado
  /product/update/{id}:
    put:
      tags:
        - Product
      summary: Update a produto by ID
      description: Atualizar Produtos pelo Id passado na requisição
      parameters:
        - in: path
          name: id
          description: Id do produto a ser atualizado
          required: true
          schema:
            type: string
      requestBody:
        description: Object containing updated product information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the product
                price:
                  type: number
                  format: double
                  description: Price of the product
                status:
                  type: string
                  description: Status of the product
                  enum: [available, unavailable]
                description:
                  type: string
                  description: Description of the product
              example:
                name: "Pizza 5 queijos"
                price: 95.00
                status: "available"
                description: "Pizza com queijo gorgonzola, mussarela, cheddar e outros"
      responses:
        200:
          description: Produto updated sucesso
        400:
          description: Invalid input, object invalid
        404:
          description: Product not found
        500:
          description: Internal server error
  /product/show/{id}:
    get:
      tags:
        - Product
      summary: Exibe os detalhes de um produto específico
      description: Retorna as informações detalhadas de um produto, como nome, preço, descrição e status.
      parameters:
        - in: path
          name: id
          description: ID do produto que deseja visualizar
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Produto encontrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID do produto
                  name:
                    type: string
                    description: Nome do produto
                  price:
                    type: number
                    description: Preço do produto
                  status:
                    type: string
                    description: Status do produto
                  description:
                    type: string
                    description: Descrição do produto
        '404':
          description: Produto não encontrado
  /product/delete/{id}:
    delete:
      tags:
        - Product
      summary: Deletar um produto
      description: Deleta um produto específico pelo ID.
      parameters:
        - in: path
          name: id
          description: ID do produto a ser deletado.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Produto deletado com sucesso.
        '404':
          description: Produto não encontrado.
        '500':
          description: Erro interno do servidor.
  /user/show:
    get:
      tags:
        - User
      summary: Mostra os detalhes do usuário logado
      description: Retorna as informações do usuário autenticado
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Nome do usuário
                  age:
                    type: integer
                    description: Idade do usuário
                  cpf:
                    type: string
                    description: CPF do usuário
                  email:
                    type: string
                    description: Endereço de e-mail do usuário
                example:
                  name: Fulano de Tal
                  age: 30
                  cpf: 123.456.789-00
                  email: fulano@example.com
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - bearerAuth: []




