swagger: '2.0'
info:
  version: 1.0.0
  title: Projeto API de Produtos/Pedidos de um delivery 
securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
paths:
  /client/create:
    post:
      tags:
        - Client
      summary: Cria um novo cliente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do cliente a ser criado
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              address:
                type: object
                properties:
                  street:
                    type: string
                  city:
                    type: string
                  state:
                    type: string
                  country:
                    type: string
                  zipCode:
                    type: string
              paymentMethod:
                type: object
                properties:
                  type:
                    type: string
                  number:
                    type: string
                  name:
                    type: string
                  expirationDate:
                    type: string
                  cvv:
                    type: string
              email:
                type: string
              password:
                type: string
              bornDate:
                type: string
                format: date
              orderHistory:
                type: array
                items:
                  type: string
              avatar:
                type: string
      responses:
        201:
          description: Cliente criado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /client/auth: 
    post:
      tags:
        - Client
      summary: Autentica um cliente existente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações de login do cliente
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Cliente autenticado com sucesso
        400:
          description: Parâmetros inválidos
        401:
          description: Credenciais inválidas
        500:
          description: Erro interno no servidor
  /client/edit:
    put:
      tags:
        - Client
      summary: Edita um cliente existente
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações do cliente a serem editadas
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              adress:
                type: array
                items:
                  type: object
                  properties:
                    street:
                      type: string
                    houseNumber:
                      type: string
                    city:
                      type: string
                    district:
                      type: string
                    landMark:
                      type: string
              paymentMethod:
                type: array
                items: {}
              email:
                type: string
              password:
                type: string
              bornDate:
                type: string
                format: date-time
              orderHistory:
                type: object
              avatar:
                type: string
      security:
        - Token: []
      responses:
        200:
          description: Cliente editado com sucesso
        400:
          description: Parâmetros inválidos
        500:
          description: Erro interno no servidor
  /client/show:
    get:
      tags:
        - Client
      summary: Retorna informações de um cliente
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Token de autenticação JWT
          required: true
          type: string
      security:
        - Token: []
      responses:
        200:
          description: Informações do cliente
          schema:
            type: object
            properties:
              name:
                type: string
              age:
                type: number
              cpf:
                type: string
              adress:
                type: array
                items:
                  type: object
                  properties:
                    street:
                      type: string
                    houseNumber:
                      type: string
                    city:
                      type: string
                    district:
                      type: string
                    landMark:
                      type: string
              paymentMethod:
                type: array
                items: {}
              email:
                type: string
              bornDate:
                type: string
                format: date-time
              orderHistory:
                type: object
              avatar:
                type: string
        401:
          description: Autenticação inválida ou não fornecida
        500:
          description: Erro interno no servidor
  /client/delete/{id}:
    delete:
      tags:
        - Client
      summary: Exclui um cliente pelo ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID do cliente a ser excluído
          required: true
          type: string
        - in: header
          name: Authorization
          description: Token de autenticação JWT
          required: true
          type: string
      security:
        - Token: []
      responses:
        204:
          description: Cliente excluído com sucesso
        401:
          description: Autenticação inválida ou não fornecida
        404:
          description: Cliente não encontrado
        500:
          description: Erro interno no servidor
  /client/address:
    post:
      tags:
        - Client
      summary: Cria um novo endereço para o cliente atual
      security:
        - JWT: []
      parameters: []
      requestBody:
        description: Objeto JSON contendo os dados do endereço
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                  example: Getulio Vargas
                houseNumber:
                  type: string
                  example: 22
                city:
                  type: string
                  example: chapeco
                district:
                  type: string
                  example: Centro
                landmark:
                  type: string
                  example: casa branca
              required:
                - street
                - houseNumber
                - city
                - district
                - landmark
      responses:
        '201':
          description: Endereço criado com sucesso
          schema:
            type: object
            properties:
              message:
                type: string
                example: Endereço criado com sucesso
        '400':
          description: Dados inválidos enviados na requisição
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dados inválidos enviados na requisição
        '401':
          description: Não autorizado
          schema:
            type: object
            properties:
              message:
                type: string
                example: Não autorizado
        '500':
          description: Erro interno do servidor
          schema:
            type: object
            properties:
              message:
                type: string
                example: Erro interno do servidor
  /client/address/delete/{id}:
    post:
      tags:
        - Client
      summary: Deletar endereço do cliente
      description: Deleta um endereço do cliente pelo seu ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do endereço a ser deletado
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Endereço deletado com sucesso
        '401':
          description: Não autorizado
        '404':
          description: Endereço não encontrado
  /client/delivery:
    get:
      tags:
        - Client
      summary: Solicitar entrega
      description: Solicita uma entrega para o endereço do cliente
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Token de autenticação
      requestBody:
        description: Dados do pedido e endereço de entrega
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                        description: ID do produto
                      quantity:
                        type: integer
                        description: Quantidade do produto
                      unitPrice:
                        type: number
                        description: Preço unitário do produto
                deliveryAddress:
                  type: object
                  properties:
                    street:
                      type: string
                      description: Nome da rua
                    houseNumber:
                      type: string
                      description: Número da casa
                    city:
                      type: string
                      description: Cidade
                    district:
                      type: string
                      description: Bairro
                    landmark:
                      type: string
                      description: Ponto de referência
              required:
                - items
                - deliveryAddress
      responses:
        '200':
          description: Pedido de entrega realizado com sucesso
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado



